AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Program that sends you messages or calls you based on overdue tasks in your todo list
Resources:
  Lambda:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: TodoList-Contacter
      Handler: index.handler
      Runtime: nodejs12.x
      Description: ""
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Role: "arn:aws:iam::711934194654:role/service-role/ToDoListContacter-role-m1jyutcb"
      InlineCode: exports.handler = function(event,context){}
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 * * ? *)
      Environment:
        Variables:
          accountSid: !Ref accountSid
          authToken: !Ref authToken
          token: !Ref token
          twilioPhone: !Ref twilioPhone
          MyNumber: !Ref MyNumber
Parameters:
  accountSid:
    Type: String
    Description: Twilio accountSid
  authToken:
    Type: String
    Description: Twilio authToken
  token:
    Type: String
    Description: Todoist Token
  twilioPhone:
    Type: String
    Description: Twilio phone number
  MyNumber:
    Type: String
    Description: My mobile number
  LambdaTimeout:
    Default: "360"
    Type: Number
    Description: The function execution time (in seconds) after which Lambda terminates the function.
  LambdaMemorySize:
    Default: "128"
    Type: Number
    Description: The function execution time (in seconds) after which Lambda terminates the function.
